#!/bin/bash

yarn workspace @redhatinsights/backstage-plugin-kafka-info export-dynamic
cd plugins/kafka-info/dist-dynamic
rm -f *.tgz
npm pack
cd ../../..
rm -f *.tgz
mv plugins/kafka-info/dist-dynamic/*.tgz .
echo "sha256-"$(shasum -a 256 *.tgz | awk '{print $1}' | xxd -r -p | base64)

