apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-kafka-info
  description: An example of a Backstage application.
  annotations:
    kafka-info/consumer-groups: example-consumer-group
  # Example for optional annotations
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
